-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 13:57:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema huzei_task10
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema huzei_task10
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `huzei_task10`;
CREATE SCHEMA `huzei_task10` DEFAULT CHARACTER SET utf8 ;
USE `huzei_task10` ;

-- -----------------------------------------------------
-- Table `huzei_task10`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huzei_task10`.`product` (
  `model` VARCHAR(50) NOT NULL,
  `maker` VARCHAR(10) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`model`),
  UNIQUE INDEX `model_UNIQUE` (`model` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `huzei_task10`.`pc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huzei_task10`.`pc` (
  `code` INT NOT NULL,
  `pc_model` VARCHAR(50) NOT NULL,
  `speed` SMALLINT NOT NULL,
  `ram` SMALLINT NOT NULL,
  `hd` REAL NOT NULL,
  `cd` VARCHAR(10) NOT NULL,
  `price` DECIMAL NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  INDEX `model_idx` (`pc_model` ASC) VISIBLE,
  UNIQUE INDEX `model_UNIQUE` (`pc_model` ASC) VISIBLE,
  CONSTRAINT `pc_model`
    FOREIGN KEY (`pc_model`)
    REFERENCES `huzei_task10`.`product` (`model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `huzei_task10`.`laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huzei_task10`.`laptop` (
  `code` INT NOT NULL,
  `laptop_model` VARCHAR(50) NOT NULL,
  `speed` SMALLINT NOT NULL,
  `ram` SMALLINT NOT NULL,
  `hd` REAL NOT NULL,
  `price` DECIMAL NULL,
  `screen` TINYINT NOT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  UNIQUE INDEX `model_UNIQUE` (`laptop_model` ASC) VISIBLE,
  CONSTRAINT `laptop_model`
    FOREIGN KEY (`laptop_model`)
    REFERENCES `huzei_task10`.`product` (`model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `huzei_task10`.`printer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huzei_task10`.`printer` (
  `code` INT NOT NULL,
  `printer_model` VARCHAR(50) NOT NULL,
  `color` CHAR(1) NOT NULL,
  `price` DECIMAL NULL,
  `type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `model_idx` (`printer_model` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE,
  UNIQUE INDEX `model_UNIQUE` (`printer_model` ASC) VISIBLE,
  CONSTRAINT `printer_model`
    FOREIGN KEY (`printer_model`)
    REFERENCES `huzei_task10`.`product` (`model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
